apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  ports:
    - protocol: 'TCP'
      port: 80 #outside facing port (external client will call this port)
      targetPort: 80 #inside port (the port that the app is listening)
  type: ClusterIP #ClusterIP will also do some load balancing but will not expose the service to outside world, only accessible from inside.
