apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks
  template:
    metadata:
      labels:
        app: tasks
    spec:
      containers:
        - name: tasks
          image: kimlngo/kub-tasks:latest
          env:
            - name: TASKS_FOLDER
              value: 'tasks'
            - name: AUTH_URL
              value: 'auth-service.default'
          volumeMounts:
            - mountPath: /app/tasks
              name: task-volume
      volumes:
        - name: task-volume
          emptyDir: {}
