apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: kimlngo/kub-users:latest
          env:
            - name: AUTH_URL
              value: 10.108.126.20 #this one is obtained from kubectl get services, it is the IP address of the auth-service running on another pod. (Manual Work)
