apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: kimlngo/kub-users:latest
          env:
            - name: AUTH_URL
              # value: 10.108.126.21 #this one is obtained from kubectl get services, it is the IP address of the auth-service running on another pod. (Manual Work)
              value: 'auth-service.default' #auth-service is from the auth-service.yaml and default is the namespace, we can get the namespace by running kubectl get namespacess
