apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: story-app
  template:
    metadata:
      labels:
        app: story-app
    spec:
      containers:
        - name: story
          image: kimlngo/kub-story-data:v1
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /app/story #/app is the WORKDIR in Dockerfile and from there the text.txt is stored in /story as coded in app.js
              name: story-volume #this name should match with the volume/name below to "wire" the connection between the app and volume
      volumes:
        - name: story-volume #define the volume with the name and type, emptyDir means empty directory
          emptyDir: {}
