apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-pvc
spec:
  volumeName: host-pv #this is the name specified in the host-pv.yaml
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi #this is amount of storage claiming, it must be less than or equal to the capacity/storage defined in the host-pv.yaml
